version: '3.2'

services:

  # Elasticsearch cluster. localhost 9200 (ensure this is open on host) --> container 9200
  # For simplicity, running only a single node here
  # To run multiple nodes on single machines: https://discuss.elastic.co/t/can-i-run-multiple-elasticsearch-nodes-on-the-same-machine/67
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: "elasticsearch:7.5.0"
    
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2048m -Xms1024m"
      ELASTIC_PASSWORD: changeme
      
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
    # Internal network for the containers
  
  logstash:
    container_name: logstash
    hostname: logstash
    image: "docker.elastic.co/logstash/logstash:7.5.0"
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx4096m -Xms2048m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  kibana:
    container_name: kibana
    hostname: kibana
    image: "kibana:7.5.0"
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch


volumes:
  elasticsearch:

networks:
  elk:
    external: true
